name: CI

on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ feature/** ]

jobs:
  build:
    name: Generate apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#     - name: Build debug apk
#        run: bash ./gradlew clean assemblePrdQatest â€”stacktrace
#      - name: Upload apk
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/*.apk
